keep_files: ['css', 'js']
include: ['_pages']
relative_permalinks: false
timezone: America/New_York
encoding: utf-8
product: Kubernetes
keywords: juju deploy kubernetes, juju kubernetes, kubernetes bundle, kubernetes ubuntu
analytics_id: UA-51016932-4
repository: whitmo/bundle-kubernetes
forkme_enabled: true
url: http://chuckbutler.github.io/bundle-kubernetes/
#url: http://localhost:4000
