keep_files: ['css', 'js']
include: ['_pages']
relative_permalinks: false
timezone: America/New_York
encoding: utf-8
product: Kubernetes
keywords: juju deploy kubernetes, juju kubernetes, kubernetes bundle, kubernetes ubuntu
analytics_id: UA-51016932-4
repository: whitmo/kubernetes-bundle
forkme_enabled: true
url: http://whitmo.github.io/kubernetes-bundle/
#url: http://localhost:4000
